-file("/opt/erl/r17b05/lib/erlang/lib/parsetools-2.0.12/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(piper_rule_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("lib/piper/permissions/piper_rule_lexer.xrl", 47).

-export([tokenize/1]).

tokenize(Text) when is_binary(Text) ->
  tokenize(binary_to_list(Text));
tokenize(Text) when is_list(Text) ->
  init(),
  case string(Text) of
    {ok, Tokens, _} ->
      {ok, Tokens};
    Error ->
      Error
  end.

init() ->
  erlang:put(br_lexer_line_count, 1),
  erlang:put(br_lexer_last_char, 0),
  erlang:put(br_lexer_char_count, 0).

clean_string([$'|Str]) ->
  re:replace(Str, "'$", <<"">>, [global, {return, binary}]);
clean_string([$"|Str]) ->
  re:replace(Str, "\"$", <<"">>, [global, {return, binary}]).

position() ->
  {get_with_default(br_lexer_line_count, 0),
   get_with_default(br_lexer_char_count, 0) - get_with_default(br_lexer_last_char, 0)}.

advance_line(TokenLine) ->
  erlang:put(br_lexer_line_count, TokenLine),
  erlang:put(br_lexer_last_char, 0),
  erlang:put(br_lexer_char_count, 0).

advance_count(Count) ->
  erlang:put(br_lexer_last_char, Count),
  set_or_add(br_lexer_char_count, Count).

get_with_default(Key, Default) ->
  case erlang:get(Key) of
    undefined ->
      Default;
    Value ->
      Value
  end.

set_or_add(Key, Value) ->
  case erlang:get(Key) of
    undefined ->
      erlang:put(Key, Value);
    OldValue ->
      erlang:put(Key, OldValue + Value)
  end.

skip_token() -> skip_token.

reserved_word("true") ->
  {boolean, position(), true};
reserved_word("false") ->
  {boolean, position(), false};
reserved_word(Word) ->
  {list_to_atom(Word), position(), list_to_binary(Word)}.

build_operator("!=") ->
  {not_equiv, position(), <<"!=">>};
build_operator("==") ->
  {equiv, position(), <<"==">>};
build_operator(">") ->
  {gt, position(), <<">">>};
build_operator("<") ->
  {lt, position(), <<"<">>};
build_operator("=<") ->
  {lte, position(), <<"=<">>};
build_operator(">=") ->
  {gte, position(), <<">=">>};
build_operator("and") ->
  {'and', position(), <<"and">>};
build_operator("or") ->
  {'or', position(), <<"or">>};
build_operator("not") ->
  {'not', position(), <<"not">>};
build_operator("in") ->
  {'in', position(), <<"in">>}.

build_regex([$/|Str]) ->
  re:replace(Str, "\/$", <<"">>, [global, {return, binary}]).

decode_arg_index([$a, $r, $g, $\[|Index]) ->
  list_to_integer(re:replace(Index, "]$", <<"">>, [global, {return, list}])).


-file("/opt/erl/r17b05/lib/erlang/lib/parsetools-2.0.12/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("lib/piper/permissions/piper_rule_lexer.erl", 365).
yystate() -> 68.

yystate(75, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line+1, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 46 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 91 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(75, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,75};
yystate(74, [103|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,74};
yystate(73, [116|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 18, Tlen);
yystate(73, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(73, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,73};
yystate(72, [13|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 20, Tlen);
yystate(72, [10|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line+1, Tlen+1, 20, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,72};
yystate(71, [111|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 18, Tlen);
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(71, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,71};
yystate(70, [115|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [91|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,70};
yystate(69, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(68, [119|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line+1, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 106, C =< 108 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 112, C =< 115 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 120, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(68, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,68};
yystate(67, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(67, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,67};
yystate(66, [114|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [110|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [109|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [108|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 113 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,66};
yystate(65, [117|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,65};
yystate(64, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line+1, Tlen+1, Action, Alen);
yystate(64, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,64};
yystate(63, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(63, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,63};
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,62};
yystate(61, [92|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 13, Tlen);
yystate(61, [47|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(61, [10|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line+1, Tlen+1, 13, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(75, Ics, Line, Tlen+1, 13, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 46 ->
    yystate(75, Ics, Line, Tlen+1, 13, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 91 ->
    yystate(75, Ics, Line, Tlen+1, 13, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(75, Ics, Line, Tlen+1, 13, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,61};
yystate(60, [105|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [104|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,60};
yystate(59, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(58, [100|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 18, Tlen);
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(58, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,58};
yystate(57, [115|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,57};
yystate(56, [32|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 19, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,56};
yystate(55, [115|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,55};
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line+1, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 46 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 91 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, [116|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,52};
yystate(51, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(50, [110|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,50};
yystate(49, [116|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,49};
yystate(48, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(47, [110|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 18, Tlen);
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(47, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,47};
yystate(46, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(46, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(46, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,46};
yystate(45, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line+1, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 46 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 91 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, [104|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 18, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(44, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,44};
yystate(43, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(42, [97|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 18, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(42, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,42};
yystate(41, [115|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 18, Tlen);
yystate(41, [110|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 18, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(41, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 114 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,41};
yystate(40, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(40, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,40};
yystate(39, [111|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 18, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(39, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 14, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,37};
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(36, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,36};
yystate(35, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line+1, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [109|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,34};
yystate(33, [97|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 18, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(33, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,33};
yystate(32, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line+1, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [105|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 18, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(31, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,31};
yystate(30, [122|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(30, [121|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 18, Tlen);
yystate(30, [100|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 18, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(30, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 120 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,30};
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [101|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,28};
yystate(27, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line+1, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [109|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 18, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(26, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,26};
yystate(25, [118|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 18, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(25, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 117 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 119, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,25};
yystate(24, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(23, [116|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 18, Tlen);
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(23, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,23};
yystate(22, [108|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 18, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(22, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,22};
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 15, Tlen);
yystate(21, [46|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 15, Tlen);
yystate(21, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 15, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Tlen+1, 15, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 15, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 15, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,21};
yystate(20, [110|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,20};
yystate(19, [92|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [39|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [10|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line+1, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(3, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(3, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(3, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(3, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,19};
yystate(18, [111|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,18};
yystate(17, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(16, [92|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 16, Tlen);
yystate(16, [34|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 16, Tlen);
yystate(16, [10|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line+1, Tlen+1, 16, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(32, Ics, Line, Tlen+1, 16, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(32, Ics, Line, Tlen+1, 16, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(32, Ics, Line, Tlen+1, 16, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(32, Ics, Line, Tlen+1, 16, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,16};
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 6, Tlen);
yystate(15, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 6, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 6, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 6, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 6, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,15};
yystate(14, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(13, [97|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,13};
yystate(12, [114|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 18, Tlen);
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(12, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,12};
yystate(11, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(10, [101|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 18, Tlen);
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(10, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,10};
yystate(9, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line+1, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, [114|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 18, Tlen);
yystate(7, [113|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(7, [112|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 18, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(7, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,7};
yystate(6, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(5, [108|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 18, Tlen);
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(5, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,5};
yystate(4, [117|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,4};
yystate(3, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line+1, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, [115|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [45|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,2};
yystate(1, [61|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 6, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,1};
yystate(0, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line+1, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars);
yyaction(1, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars);
yyaction(2, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars);
yyaction(3, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars);
yyaction(4, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars);
yyaction(5, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars);
yyaction(6, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars);
yyaction(7, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars);
yyaction(8, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars);
yyaction(9, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars);
yyaction(10, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars);
yyaction(11, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars);
yyaction(12, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars);
yyaction(13, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars);
yyaction(14, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars);
yyaction(15, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars);
yyaction(16, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars);
yyaction(17, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars);
yyaction(18, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars);
yyaction(19, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 23).
yyaction_0(TokenChars) ->
     advance_count (length (TokenChars)), { token, reserved_word (TokenChars) } .

-compile({inline,yyaction_1/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 24).
yyaction_1(TokenChars) ->
     advance_count (length (TokenChars)), { token, { arg, position (), decode_arg_index (TokenChars) } } .

-compile({inline,yyaction_2/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 25).
yyaction_2(TokenChars) ->
     advance_count (length (TokenChars)), { token, { arg, position (), nil } } .

-compile({inline,yyaction_3/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 26).
yyaction_3(TokenChars) ->
     advance_count (length (TokenChars)), { token, { arg, position (), nil } } .

-compile({inline,yyaction_4/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 27).
yyaction_4(TokenChars) ->
     advance_count (length (TokenChars)), { token, { option, position (), nil } } .

-compile({inline,yyaction_5/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 28).
yyaction_5(TokenChars) ->
     advance_count (length (TokenChars)), { token, { option, position (), nil } } .

-compile({inline,yyaction_6/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 29).
yyaction_6(TokenChars) ->
     advance_count (length (TokenChars)), { token, build_operator (TokenChars) } .

-compile({inline,yyaction_7/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 30).
yyaction_7(TokenChars) ->
     advance_count (length (TokenChars)), { token, { lparen, position (), << "(" >> } } .

-compile({inline,yyaction_8/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 31).
yyaction_8(TokenChars) ->
     advance_count (length (TokenChars)), { token, { rparen, position (), << ")" >> } } .

-compile({inline,yyaction_9/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 32).
yyaction_9(TokenChars) ->
     advance_count (length (TokenChars)), { token, { lbracket, position (), << "[" >> } } .

-compile({inline,yyaction_10/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 33).
yyaction_10(TokenChars) ->
     advance_count (length (TokenChars)), { token, { rbracket, position (), << "]" >> } } .

-compile({inline,yyaction_11/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 34).
yyaction_11(TokenChars) ->
     advance_count (length (TokenChars)), { token, { colon, position (), << ":" >> } } .

-compile({inline,yyaction_12/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 35).
yyaction_12(TokenChars) ->
     advance_count (length (TokenChars)), { token, { comma, position (), << "," >> } } .

-compile({inline,yyaction_13/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 36).
yyaction_13(TokenChars) ->
     advance_count (length (TokenChars)), { token, { regex, position (), build_regex (TokenChars) } } .

-compile({inline,yyaction_14/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 37).
yyaction_14(TokenChars) ->
     advance_count (length (TokenChars)), { token, { float, position (), list_to_float (TokenChars) } } .

-compile({inline,yyaction_15/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 38).
yyaction_15(TokenChars) ->
     advance_count (length (TokenChars)), { token, { integer, position (), list_to_integer (TokenChars) } } .

-compile({inline,yyaction_16/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 39).
yyaction_16(TokenChars) ->
     advance_count (length (TokenChars)), { token, { dqstring, position (), clean_string (TokenChars) } } .

-compile({inline,yyaction_17/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 40).
yyaction_17(TokenChars) ->
     advance_count (length (TokenChars)), { token, { sqstring, position (), clean_string (TokenChars) } } .

-compile({inline,yyaction_18/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 41).
yyaction_18(TokenChars) ->
     advance_count (length (TokenChars)), { token, { string, position (), list_to_binary (TokenChars) } } .

-compile({inline,yyaction_19/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 42).
yyaction_19(TokenChars) ->
     advance_count (length (TokenChars)), skip_token () .

-compile({inline,yyaction_20/1}).
-file("lib/piper/permissions/piper_rule_lexer.xrl", 43).
yyaction_20(TokenLine) ->
     advance_line (TokenLine), skip_token () .

-file("/opt/erl/r17b05/lib/erlang/lib/parsetools-2.0.12/include/leexinc.hrl", 282).
